### ISSUE TITLE
status 

### ISSUE THREAD

**Issue by hubbigaming** [jjl/get_iplayer#7]
is the project finished? im a java developer and could help.

**Comment by jjl** [comment]
the code is so horrible i couldn't bear to keep maintaining it. i did have a go at restarting it from scratch but it's all so impossible to determine what it's doing that i gave up on that too..

i am told square penguin is nominally the current maintainer, though i've no idea who that is and i don't think it's a particularly active maintainership (and i really can't blame them, did i mention how horrible the code is?).

in any case, the way things have been trending, i imagine it won't be too long before the bbc neuters get_iplayer in some crucial way, so it seems like a waste of effort to maintain.
